---
title: "Untitled"
author: "Hannah Cooney"
date: "2026-03-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
```

```{r}
# Load the data
load("obesity.Rda")

obesity <- obesity |>
  mutate(diabetes = ifelse(diabetes == "No", 0, 1)) |>
  select(-c("nr", "medstatin", "medglucose", "CVD", "MI", "angina", "stroke", "death")) |>
  filter(diabetes != "NA")

as.numeric(obesity$diabetes)
summary(obesity)

```

```{r}
library(dagitty)
library(ggplot2)
library(GGally)
library(gridExtra)

## Specify the DAG
g.diabetes <- dagitty('dag {
  
  education     [pos="-4,1"]
  income        [pos="-4,-1"]
  alcohol  [exposure,pos="-2,0"]
  current.smoking [exposure,pos="-2,0"]
  sex           [pos="-2,2"]
  medhyper      [pos="0,3"]
  bmi           [pos="1,2"]
  waist         [pos="1,0"]
  age           [pos="3,1"]
  SYSBP         [pos="2,-1"]
  DIABP         [pos="2,-1"]
  diabetes      [outcome,pos="0,-1"]

  education -> {income}
  income -> diabetes
  sex -> {diabetes bmi}
  medhyper -> {SYSBP DIABP}
  bmi -> waist
  waist -> diabetes
  age -> {bmi SYSBP DIABP}
  alcohol -> {SYSBP DIABP}
  current.smoking -> {SYSBP DIABP}
  SYSBP -> diabetes
  DIABP -> diabetes
}
')

## Plot DAG
plot(g.diabetes)
```

```{r}
print(r)
```

```{r}
r <- localTests(g.diabetes, obesity, type = "cis.pillai")

r <- r[p.adjust(r$p.value) < 0.05, ]

r <- r[order(r$p.value), ]

par(mar = c(4, 8.5, 1.5, 0.5))

plotLocalTestResults(r, bty = "n", xlim = c(-0.4, 0.4), ylim = c(0.1, 3.1), axis.pars = list(las = 1, lty = 0))
```
